#pragma once

// 
// MyGeometries.h   ---  Header file for MyGeometries.cpp.
// 
//   Sets up and renders 
//     - the ground plane, and
//     - the surface of rotation
//   for the Math 155A project #4.
//
//

#include "GlGeomCylinder.h"
#include "GlGeomSphere.h"

// **************************
// Information for loading textures
// **************************
const int NumTextures = 5;
//unsigned int TextureNames[NumTextures];     // Texture names generated by OpenGL
//const char* TextureFiles[NumTextures];

// *******************************
// Two spheres and a cylinder
// *******************************
//GlGeomSphere texSphere;
//GlGeomCylinder texCylinder;

//
// Function Prototypes
//
void MySetupSurfaces();                // Called once, before rendering begins.
void SetupForTextures();               // Loads textures, sets Phong material
void MyRemeshGeometries();             // Called when mesh changes, must update resolutions.
void SamsRemeshCircularSurf();      // Update resolution of the surface of rotation.

void MyRenderGeometries();            // Called to render the two surfaces
void SamsRenderCircularSurf();      // Renders the meshed circular surface



